# OPTION NOTE:
# ansible_ssh_host=
# ansible_ssh_port=22
# ansible_ssh_user=
# ansible_ssh_private_key_file=
# ansible_ssh_pass=
all:
    hosts:
        autonode:
            ansible_ssh_host: 10.188.123.123
            ansible_ssh_user: nyphoon
            ansible_ssh_private_key_file: ~/.ssh/ansible/id_rsa
            wd: /Users/nyphoon/Desktop/ansible

        localhost:
            ansible_connection: local
